### ISSUE TITLE
DB closed exception when shutting adapter down

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.envertech-pv#111]
After stopping the adapter using admin / instance interface the following errors have been logged:
```
host.pi4 | 2023-09-13 17:11:31.213 | info | instance system.adapter.envertech-pv.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
envertech-pv.0 | 2023-09-13 17:11:31.103 | error | DB closed
envertech-pv.0 | 2023-09-13 17:11:31.103 | error | Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25) at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:657:40) at envertech_pv.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5886:35)
envertech-pv.0 | 2023-09-13 17:11:31.100 | error | unhandled promise rejection: DB closed
envertech-pv.0 | 2023-09-13 17:11:31.099 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
envertech-pv.0 | 2023-09-13 17:11:31.096 | warn | get state error: Connection is closed.
host.pi4 | 2023-09-13 17:11:30.711 | info | stopInstance system.adapter.envertech-pv.0 send kill signal
envertech-pv.0 | 2023-09-13 17:11:30.585 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
envertech-pv.0 | 2023-09-13 17:11:30.584 | info | terminating
envertech-pv.0 | 2023-09-13 17:11:30.580 | info | Got terminate signal TERMINATE_YOURSELF
host.pi4 | 2023-09-13 17:11:30.568 | info | stopInstance system.adapter.envertech-pv.0 (force=false, process=true)
host.pi4 | 2023-09-13 17:11:30.568 | info | "system.adapter.envertech-pv.0" disabled
```

Adapter 1.0.2
js-controller 4.0.24
node 18

**Comment by mcm1957** [comment]
problem cannot be reproduced.
